### ISSUE TITLE
number of lines has decreased

### ISSUE THREAD

**Issue by classmate01** [meizhong986/WhisperJAV#9]
Hello!
I Just noticed after the latest update, the number of lines I am getting has decreased, not sure about the others...

**Comment by meizhong986** [comment]
Can you check what is your VAD Threshold?

**Comment by classmate01** [comment]
I use the default 0.35 and using WhisperJAV_v0_7b

**Comment by meizhong986** [comment]
Yes it seems that your observation is correct.
Since the last update (ca. a week ago) the code started to use the latest
VAD update which is the Silero VAD 0.51 version.
That version of VAD doesn't perform well with typical JAV movies: noise and
music.
May I ask if you're using WhipserJAV for JAV or non-JAV movies?

**Comment by classmate01** [comment]
I'm using it for JAV movies.
Should I adjust the VAD threshold to match up with Silero's VAD v0.51?

Thank you for your follow-up and I really appreciate it!

**Comment by meizhong986** [comment]
That won't help in this situation. The problem is that the new Silero VAD
5x releases are suited for podcasts and other clean speech audio.
Better solution is to fix it inside WhisperJAV by using the older release
of Silero.
I'll look into it

**Comment by meizhong986** [comment]
I just pushed a new update to force using SileroVAD 4.0 version. 
Give it  a try now, let me know.

**Comment by classmate01** [comment]
I believe its now working!! Thank you so much!
